const homeController=require('../app/http/controllers/homeController')
const adminController=require('../app/http/controllers/admin/adminController')
const authController=require('../app/http/controllers/authController')
const paymentController=require('../app/http/controllers/paymentController')
const servicesController=require('../app/http/controllers/servicesController')
const guest=require('../app/http/middlewares/guest')
const admin=require('../app/http/middlewares/admin')
const auth=require('../app/http/middlewares/auth')
function initRoutes(app){
    app.get('/',homeController().index)
    /*
    app.get('/cart',(req,res)=>{
        res.render('customers/cart')
    }) 
    */
    app.get('/dashboard',auth,homeController().dashboard)
    app.get('/admin',admin,adminController().admin)
    app.get('/admin/search',admin,adminController().search)
    app.post('/profile',admin,adminController().post_search)
    app.get('/profile',admin,adminController().profile)
    app.get('/admin/complains',admin,adminController().complains)
    app.get('/admin/transactions',admin,adminController().transactions)
    app.get('/admin/fixed_deposits',admin,adminController().fixed)
    app.get('/admin/loans',admin,adminController().loan)
    app.get('/pay',auth,homeController().pay)
    app.get('/login',guest,authController().login)
    app.get('/transfer',auth,paymentController().transfer)
    app.post('/transfer_post',paymentController().transfer_post)
    app.post('/loan',auth,servicesController().loan_post)
    app.get('/valid',auth,paymentController().validget)
    app.post('/valid',auth,paymentController().valid)
    app.post('/fd',auth,servicesController().fd_post)
    app.post('/status',auth,paymentController().status)
    app.post('/topup',auth,paymentController().topup)
    app.get('/topup_dpay',auth,paymentController().topupget)
    app.get('/finalsend',auth,paymentController().finalsend)
    app.get('/recharge',auth,paymentController().recharge)
    app.get('/utilities',auth,paymentController().utilities)
    app.get('/fixeddeposit',auth,servicesController().fixed_deposit)
    app.get('/transactions',auth,servicesController().transactions)
    app.get('/downloads',auth,servicesController().downloads)
    app.get('/shares',auth,servicesController().shares)
    app.get('/loan',auth,servicesController().loan)
    app.get('/interest',auth,servicesController().interest)
    app.get('/aboutus',auth,homeController().aboutus)
    app.get('/customercare',auth,homeController().customercare)
    app.post('/complain',homeController().complain)
    app.get('/complain',auth,homeController().customerget)
    app.get('/utilities',auth,paymentController().utilities)
    app.get('/terms',auth,servicesController().terms)
    app.get('/register',guest,authController().register)
    app.post('/login',guest,authController().postLogin)
    app.post('/register',guest,authController().postRegister)
    app.post('/logout',auth,authController().logout)
    
}

module.exports=initRoutes